<?php
/**
 * Created by PhpStorm.
 * User: shamo
 * Date: 1/17/2017
 * Time: 2:45 PM
 */
return [
    'Manage'=>[
        'menu'=>[
            'index',
            'add',
            'edit',
            'del',
            'modify_state',
        ],
        'admin'=>[
            'index',
            'add',
            'edit',
            'del',
            'modify_state',
        ],
        'adminGroup'=>[
            'index',
            'add',
            'edit',
            'del',
            'modify_state',
        ],
        'auth'=>[
            'index',
            'edit',
        ],
        'smsLog'=>[
            'index',
        ],
        'account'=>[
            'index',
            'add',
            'edit',
            'modify_state',
            'examine',
            'del',
        ],
        'personAuth'=>[
            'index',
            'del',
            'add',
            'edit',
            'examine',
        ],
        'companyAuth'=>[
            'index',
            'del',
            'examine',
        ],
        'factorApply'=>[
            'index',
            'del',
            'examine',
            'modify_state',
        ],
        'demandList'=>[
            'index',
            'del',
            'edit',
            'examine',
            'modify_state',
        ],
        'smsTemplate'=>[
            'index',
            'del',
            'add',
            'edit',
        ],
        'smsSend'=>[
            'index',
        ],

        'district'=>[
            'index',
            'del',
            'add',
            'edit',
        ],
        'policyType'=>[
            'index',
            'del',
            'add',
            'edit',
        ],
        'policy'=>[
            'index',
            'del',
            'add',
            'edit',
        ],
        'policyOrder'=>[
            'index',
        ],
        'serviceRange'=>[
            'index',
            'del',
            'add',
            'edit',
        ],
        'demandRange'=>[
            'index',
            'del',
            'add',
            'edit',
        ],
    ],
];